### ISSUE TITLE
package bc missing from install

### ISSUE THREAD

**Issue by dantrevino** [jriguera/packer-rpibuilder-vagrant#4]
fyi it looks like bc is not installed on the buster image, and that makes the vagrant build fail.

**Comment by jriguera** [comment]
Ok, thanks! I will have a look

**Comment by jriguera** [comment]
Ok, I think you are using an old version of vagrant, you have to change to `"jriguera/rpibuilder-buster-10.2-i386"`
The package is installed here: https://github.com/jriguera/packer-rpibuilder-vagrant/blob/fa380f8a36eeff12a375f04c78d6f692cd946527/scripts/packages.sh#L7

**Comment by jriguera** [comment]
I have updated the readme: https://github.com/jriguera/packer-rpibuilder-vagrant/blob/master/README.md#usage

Closing the issue.
Thanks for reporting,
Jose

**Comment by dantrevino** [comment]
Thank you!
