### ISSUE TITLE
REQ: Bigger default drive

### ISSUE THREAD

**Issue by dantrevino** [jriguera/packer-rpibuilder-vagrant#5]
Is it possible to bump up the drive space to 50GB?  I've tried doing this myself, but am failing atm.  Since its a dynamic disk, it shouldnt matter, right?

My attempted builds keep failing due to space.

**Comment by jriguera** [comment]
Yep, it should not matter. I will bump the disk size to 50G and push the new version.

**Comment by dantrevino** [comment]
Awesome, thanks!

**Comment by jriguera** [comment]
I have updated Debian Buster to 10.4 and increased the disk size.

Please use something like this in your vagrantfile:
```
  config.vm.define :rpigen do |rpigen|
      # Every Vagrant virtual environment requires a box to build off of.
      rpigen.vm.box = "jriguera/rpibuilder-buster-10.4-i386"
  end
```

**Comment by dantrevino** [comment]
ty
